[build]
  publish = "dist/public"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/api/*"
  to = "https://final-production-8f03.up.railway.app/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
